# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://3Diot.github.io/blog/"

git_url = "https://github.com/3Diot/blog/tree/main/"

def custom_doc_links(name): return None
