# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "000_core.ipynb",
         "convertNb": "000_core.ipynb",
         "cleanCell": "000_core.ipynb",
         "processCode": "000_core.ipynb",
         "getFlags": "000_core.ipynb",
         "makeDetails": "000_core.ipynb",
         "processSource": "000_core.ipynb",
         "processOutput": "000_core.ipynb",
         "runit": "000_core.ipynb"}

modules = ["core.py"]

doc_url = "https://3Diot.github.io/blog/"

git_url = "https://github.com/3Diot/blog/tree/main/"

def custom_doc_links(name): return None
